require("tree-sitter-manager").setup {
  ensure_installed = {
    "bash",
    "bibtex",
    "c",
    "c_sharp",
    "clojure",
    "cmake",
    "comment",
    "cpp",
    "css",
    "diff",
    "dockerfile",
    "doxygen",
    "fennel",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "glimmer",
    "go",
    "gomod",
    "gosum",
    "graphql",
    "hcl",
    "html",
    "htmldjango",
    "http",
    "ini",
    "java",
    "javascript",
    "jsdoc",
    "json",
    "julia",
    "kotlin",
    "latex",
    "make",
    "nginx",
    "nix",
    "php",
    "prisma",
    "proto",
    "python",
    "ql",
    "query",
    "r",
    "regex",
    "requirements",
    "ruby",
    "rust",
    "sql",
    "ssh_config",
    "strace",
    "svelte",
    "terraform",
    "toml",
    "tsx",
    "twig",
    "typescript",
    "typst",
    "vim",
    "vimdoc",
    "vue",
    "xml",
    "yaml",
    "zig",
  },

  auto_install = true,
}

vim.wo.foldmethod = "expr"
vim.wo.foldexpr = "v:lua.vim.treesitter.foldexpr()"
vim.wo.foldenable = false
