#!/bin/bash

shdl() { curl -O $(curl -s http://sci-hub.tw/"$@" | grep location.href | grep -o http.*pdf) ; }
se() { du -a ~/bin/* | grep -v 'external' | awk '{print $2}' | sk | xargs -r $EDITOR ; }
vf() { sk --preview='highlight --out-format=ansi --force {}' | xargs -r -I % $EDITOR % ; }
gf() { OUTPUT=$(sk --ansi -i -c 'ag --color "{}"') ; FILE=$(echo "$OUTPUT" | cut -d ':' -f 1) ; LINE=$(echo "$OUTPUT" | cut -d ':' -f 2); $EDITOR +"$LINE" "$FILE" ; }
lod() { pacman -Qi "${1}" | sed -n '/^Optional/,$p' | sed '/^Required/q' | head -n -1 | cut -c19- | cut -d: -f1 | grep -v installed ; }
randmov() { curl -s https://www.imdb.com/list/ls062548361/export | shuf -n 1 | cut -d, -f6; }
